### ISSUE TITLE
diff-merge 依赖

### ISSUE THREAD

**Issue by xujianhai** [nighca/differ#2]
你这个依赖 diff-merge@1.0.1 的版本, 但是现在没有这个版本了，看github上，应该是名字换成了 universal-diff, 但是，universal-diff 并没有 1.0.1 的版本，你看看有什么好的办法？
关注的原因 : 我使用 universal-diff的最新版本根本无法还原html demo的效果

**Comment by nighca** [comment]
我重新实现了下，做成一个 react 组件，也更新了下依赖，基于最新的 `universal-diff`。
你看能不能直接用，用不了可以参考[这里的实现](https://github.com/nighca/differ/blob/master/src/index.js)
